// RBAC constants: stable permission & role identifiers plus role->permission mapping.
// Extend by adding new PERMISSIONS keys and including them in relevant ROLES_PERMISSIONS entries.
export const PERMISSIONS = {
  // Core / Dashboard
  VIEW_DASHBOARD: "VIEW:DASHBOARD",

  // Users (existing internal management)
  READ_USERS: "READ:USERS",
  EDIT_USERS: "EDIT:USERS",
  DELETE_USERS: "MANAGE:USERS",
  VIEW_USERS: "VIEW:USERS",

  // States
  READ_STATES: "READ:STATES",
  EDIT_STATES: "EDIT:STATES",
  DELETE_STATES: "DELETE:STATES",
  VIEW_STATES: "VIEW:STATES",

  // StockAdjustments
  READ_STOCK_ADJUSTMENTS: "READ:STOCK_ADJUSTMENTS",
  CREATE_STOCK_ADJUSTMENTS: "CREATE:STOCK_ADJUSTMENTS",
  VIEW_STOCK_ADJUSTMENTS: "VIEW:STOCK_ADJUSTMENTS",

  // Stocks
  READ_STOCKS: "READ:STOCKS",
  VIEW_STOCKS: "VIEW:STOCKS",

  // Cities
  READ_CITIES: "READ:CITIES",
  EDIT_CITIES: "EDIT:CITIES",
  DELETE_CITIES: "DELETE:CITIES",
  VIEW_CITIES: "VIEW:CITIES",

  // Companies
  READ_COMPANIES: "READ:COMPANIES",
  EDIT_COMPANIES: "EDIT:COMPANIES",
  DELETE_COMPANIES: "DELETE:COMPANIES",
  VIEW_COMPANIES: "VIEW:COMPANIES",

  // Sites
  READ_SITES: "READ:SITES", //get
  CREATE_SITES: "CREATE:SITES", //post
  EDIT_SITES: "EDIT:SITES", //put
  DELETE_SITES: "DELETE:SITES", //delete
  VIEW_SITES: "VIEW:SITES", //view

  // designations
  READ_DESIGNATIONS: "READ:DESIGNATIONS", //get
  CREATE_DESIGNATIONS: "CREATE:DESIGNATIONS", //post
  EDIT_DESIGNATIONS: "EDIT:DESIGNATIONS", //put
  DELETE_DESIGNATIONS: "DELETE:DESIGNATIONS", //delete
  VIEW_DESIGNATIONS: "VIEW:DESIGNATIONS", //

  // Departments
  READ_DEPARTMENTS: "READ:DEPARTMENTS",
  EDIT_DEPARTMENTS: "EDIT:DEPARTMENTS",
  DELETE_DEPARTMENTS: "DELETE:DEPARTMENTS",
  VIEW_DEPARTMENTS: "VIEW:DEPARTMENTS",

  // Notices
  READ_NOTICES: "READ:NOTICES",
  CREATE_NOTICES: "CREATE:NOTICES",
  EDIT_NOTICES: "EDIT:NOTICES",
  DELETE_NOTICES: "DELETE:NOTICES",
  VIEW_NOTICES: "VIEW:NOTICES",

  // Employees
  READ_EMPLOYEES: "READ:EMPLOYEES",
  EDIT_EMPLOYEES: "EDIT:EMPLOYEES",
  DELETE_EMPLOYEES: "DELETE:EMPLOYEES",
  VIEW_EMPLOYEES: "VIEW:EMPLOYEES",

  // Categories
  READ_CATEGORIES: "READ:CATEGORIES",
  EDIT_CATEGORIES: "EDIT:CATEGORIES",
  DELETE_CATEGORIES: "DELETE:CATEGORIES",
  VIEW_CATEGORIES: "VIEW:CATEGORIES",

  // SkillSets
  READ_SKILLSETS: "READ:SKILLSETS",
  EDIT_SKILLSETS: "EDIT:SKILLSETS",
  DELETE_SKILLSETS: "DELETE:SKILLSETS",
  VIEW_SKILLSETS: "VIEW:SKILLSETS",

  // ManpowerSuppliers
  READ_MANPOWER_SUPPLIERS: "READ:MANPOWER:SUPPLIERS",
  EDIT_MANPOWER_SUPPLIERS: "EDIT:MANPOWER:SUPPLIERS",
  DELETE_MANPOWER_SUPPLIERS: "DELETE:MANPOWER:SUPPLIERS",
  VIEW_MANPOWER_SUPPLIERS: "VIEW:MANPOWER:SUPPLIERS",

  // Manpowers
  READ_MANPOWER: "READ:MANPOWER",
  EDIT_MANPOWER: "EDIT:MANPOWER",
  DELETE_MANPOWER: "DELETE:MANPOWER",
  VIEW_MANPOWER: "VIEW:MANPOWER",

  // MinimumWages
  READ_MIN_WAGES: "READ:MIN_WAGES",
  EDIT_MIN_WAGES: "EDIT:MIN_WAGES",
  DELETE_MIN_WAGES: "DELETE:MIN_WAGES",
  VIEW_MIN_WAGES: "VIEW:MIN_WAGES",

  // AssignManpowers Test permission
  READ_MANPOWER_ASSIGNMENTS: "READ:MANPOWER:ASSIGNMENTS",
  CREATE_MANPOWER_ASSIGNMENTS: "CREATE:MANPOWER:ASSIGNMENTS",
  EDIT_MANPOWER_ASSIGNMENTS: "EDIT:MANPOWER:ASSIGNMENTS",
  DELETE_MANPOWER_ASSIGNMENTS: "DELETE:MANPOWER:ASSIGNMENTS",
  VIEW_MANPOWER_ASSIGNMENTS: "VIEW:MANPOWER:ASSIGNMENTS",

  // Manpower Transfer Test permissions
  READ_MANPOWER_TRANSFERS: "READ:MANPOWER:TRANSFERS",
  CREATE_MANPOWER_TRANSFERS: "CREATE:MANPOWER:TRANSFERS",
  EDIT_MANPOWER_TRANSFERS: "EDIT:MANPOWER:TRANSFERS",
  DELETE_MANPOWER_TRANSFERS: "DELETE:MANPOWER:TRANSFERS",
  APPROVE_MANPOWER_TRANSFERS: "APPROVE:MANPOWER:TRANSFERS",
  VIEW_MANPOWER_TRANSFERS: "VIEW:MANPOWER:TRANSFERS",

  // Attendance  Test permissions
  READ_ATTENDANCES: "READ:ATTENDANCES",
  CREATE_ATTENDANCES: "CREATE:ATTENDANCES",
  EDIT_ATTENDANCES: "EDIT:ATTENDANCES",
  DELETE_ATTENDANCES: "DELETE:ATTENDANCES",
  VIEW_ATTENDANCES: "VIEW:ATTENDANCES",

  // Payrolls Permissions
  READ_PAYSLIPS: "READ:PAYSLIPS",
  GENERATE_PAYSLIPS: "GENERATE:PAYSLIPS",

  // DailyConsumptions
  READ_DAILY_CONSUMPTIONS: "READ:DAILY_CONSUMPTIONS",
  CREATE_DAILY_CONSUMPTIONS: "CREATE:DAILY_CONSUMPTIONS",
  VIEW_DAILY_CONSUMPTIONS: "VIEW:DAILY_CONSUMPTIONS",

  READ_PURCHASE_ORDERS: "READ:PURCHASE_ORDERS",
  CREATE_PURCHASE_ORDERS: "CREATE:PURCHASE_ORDERS",
  EDIT_PURCHASE_ORDERS: "EDIT:PURCHASE_ORDERS",
  DELETE_PURCHASE_ORDERS: "DELETE:PURCHASE_ORDERS",
  APPROVE_PURCHASE_ORDERS_L1: "APPROVE:PURCHASE_ORDERS:L1",
  APPROVE_PURCHASE_ORDERS_L2: "APPROVE:PURCHASE_ORDERS:L2",
  COMPLETE_PURCHASE_ORDERS: "COMPLETE:PURCHASE_ORDERS",
  SUSPEND_PURCHASE_ORDERS: "SUSPEND:PURCHASE_ORDERS",
  UPDATE_PURCHASE_ORDER_REMARKS: "UPDATE:PURCHASE_ORDER:REMARKS",
  UPDATE_PURCHASE_ORDER_BILL_STATUS: "UPDATE:PURCHASE_ORDER:BILL_STATUS",

  READ_WORK_ORDER_BILLS: "READ:WORK_ORDER_BILLS",
  CREATE_WORK_ORDER_BILLS: "CREATE:WORK_ORDER_BILLS",
  EDIT_WORK_ORDER_BILLS: "EDIT:WORK_ORDER_BILLS",
  DELETE_WORK_ORDER_BILLS: "DELETE:WORK_ORDER_BILLS",

  READ_INWARD_DELIVERY_CHALLAN: "READ:INWARD_DELIVERY_CHALLAN",
  CREATE_INWARD_DELIVERY_CHALLAN: "CREATE:INWARD_DELIVERY_CHALLAN",
  EDIT_INWARD_DELIVERY_CHALLAN: "EDIT:INWARD_DELIVERY_CHALLAN",

  // Inward bills
  READ_INWARD_BILL: "READ:INWARD_BILL",
  EDIT_INWARD_BILL: "EDIT:INWARD_BILL",

  //inward bill paymet
  ADD_INWARD_BILL_PAYMENT: "ADD:INWARD_BILL_PAYMENT",
  DELETE_INWARD_BILL_PAYMENT: "DELETE:INWARD_BILL_PAYMENT",

  // Outward Delivery Challan permissions
  READ_OUTWARD_DELIVERY_CHALLAN: "READ:OUTWARD_DELIVERY_CHALLAN",
  CREATE_OUTWARD_DELIVERY_CHALLAN: "CREATE:OUTWARD_DELIVERY_CHALLAN",
  APPROVE_OUTWARD_DELIVERY_CHALLAN: "APPROVE:OUTWARD_DELIVERY_CHALLAN",
  ACCEPT_OUTWARD_DELIVERY_CHALLAN: "ACCEPT:OUTWARD_DELIVERY_CHALLAN",

  READ_WORK_ORDERS: "READ:WORK_ORDERS",
  CREATE_WORK_ORDERS: "CREATE:WORK_ORDERS",
  EDIT_WORK_ORDERS: "EDIT:WORK_ORDERS",
  DELETE_WORK_ORDERS: "DELETE:WORK_ORDERS",

  // Unit permissions
  READ_UNITS: "READ:UNITS",
  EDIT_UNITS: "EDIT:UNITS",
  DELETE_UNITS: "DELETE:UNITS",
  // Asset Group permissions
  READ_ASSET_GROUPS: "READ:ASSET_GROUPS",
  EDIT_ASSET_GROUPS: "EDIT:ASSET_GROUPS",
  DELETE_ASSET_GROUPS: "DELETE:ASSET_GROUPS",
  // Asset Category permissions
  READ_ASSET_CATEGORIES: "READ:ASSET_CATEGORIES",
  EDIT_ASSET_CATEGORIES: "EDIT:ASSET_CATEGORIES",
  DELETE_ASSET_CATEGORIES: "DELETE:ASSET_CATEGORIES",
  // Item Category permissions
  READ_ITEM_CATEGORIES: "READ:ITEM:CATEGORIES",
  CREATE_ITEM_CATEGORIES: "CREATE:ITEM:CATEGORIES",
  EDIT_ITEM_CATEGORIES: "EDIT:ITEM:CATEGORIES",
  DELETE_ITEM_CATEGORIES: "DELETE:ITEM:CATEGORIES",
  // Items permissions
  READ_ITEMS: "READ:ITEMS",
  CREATE_ITEMS: "CREATE:ITEMS",
  EDIT_ITEMS: "EDIT:ITEMS",
  DELETE_ITEMS: "DELETE:ITEMS",
  // Billing Address permissions
  READ_BILLING_ADDRESSES: "READ:BILLING:ADDRESSES",
  CREATE_BILLING_ADDRESSES: "CREATE:BILLING:ADDRESSES",
  EDIT_BILLING_ADDRESSES: "EDIT:BILLING:ADDRESSES",
  DELETE_BILLING_ADDRESSES: "DELETE:BILLING:ADDRESSES",
  // Vendor permissions
  READ_VENDORS: "READ:VENDORS",
  CREATE_VENDORS: "CREATE:VENDORS",
  EDIT_VENDORS: "EDIT:VENDORS",
  DELETE_VENDORS: "DELETE:VENDORS",
  // BOQ permissions
  READ_BOQS: "READ:BOQS",
  EDIT_BOQS: "EDIT:BOQS",
  DELETE_BOQS: "DELETE:BOQS",
  // Daily Progress permissions
  READ_DAILY_PROGRESSES: "READ:DAILY_PROGRESSES",
  EDIT_DAILY_PROGRESSES: "EDIT:DAILY_PROGRESSES",
  DELETE_DAILY_PROGRESSES: "DELETE:DAILY_PROGRESSES",
  // Payment Terms permissions
  READ_PAYMENT_TERMS: "READ:PAYMENT:TERMS",
  CREATE_PAYMENT_TERMS: "CREATE:PAYMENT:TERMS",
  EDIT_PAYMENT_TERMS: "EDIT:PAYMENT:TERMS",
  DELETE_PAYMENT_TERMS: "DELETE:PAYMENT:TERMS",

  // Cashbook Heads permissions
  READ_CASHBOOK_HEADS: "READ:CASHBOOK_HEADS",
  EDIT_CASHBOOK_HEADS: "EDIT:CASHBOOK_HEADS",
  DELETE_CASHBOOK_HEADS: "DELETE:CASHBOOK_HEADS",
  // Cashbook Budgets permissions
  READ_CASHBOOK_BUDGETS: "READ:CASHBOOK_BUDGETS",
  CREATE_CASHBOOK_BUDGETS: "CREATE:CASHBOOK_BUDGETS",
  EDIT_CASHBOOK_BUDGETS: "EDIT:CASHBOOK_BUDGETS",
  DELETE_CASHBOOK_BUDGETS: "DELETE:CASHBOOK_BUDGETS",
  // Cashbook permissions
  READ_CASHBOOKS: "READ:CASHBOOKS",
  CREATE_CASHBOOKS: "CREATE:CASHBOOKS",
  EDIT_CASHBOOKS: "EDIT:CASHBOOKS",
  DELETE_CASHBOOKS: "DELETE:CASHBOOKS",
  // Indent permissions
  READ_INDENTS: "READ:INDENTS",
  CREATE_INDENTS: "CREATE:INDENTS",
  EDIT_INDENTS: "EDIT:INDENTS",
  DELETE_INDENTS: "DELETE:INDENTS",
  APPROVE_INDENTS_L1: "APPROVE:INDENTS:L1",
  APPROVE_INDENTS_L2: "APPROVE:INDENTS:L2",
  COMPLETE_INDENTS: "COMPLETE:INDENTS",
  SUSPEND_INDENTS: "SUSPEND:INDENTS",
  GENERATE_PO_FROM_INDENT: "GENERATE_PO:FROM_INDENT",

  // Site Budget permissions
  READ_SITE_BUDGETS: "READ:SITE:BUDGETS",
  CREATE_SITE_BUDGETS: "CREATE:SITE:BUDGETS",
  EDIT_SITE_BUDGETS: "EDIT:SITE:BUDGETS",
  DELETE_SITE_BUDGETS: "DELETE:SITE:BUDGETS",

  // Rental Category permissions
  READ_RENTAL_CATEGORIES: "READ:RENTAL:CATEGORIES",
  EDIT_RENTAL_CATEGORIES: "EDIT:RENTAL:CATEGORIES",
  DELETE_RENTAL_CATEGORIES: "DELETE:RENTAL:CATEGORIES",
  // Rent Type permissions
  READ_RENT_TYPES: "READ:RENT:TYPES",
  EDIT_RENT_TYPES: "EDIT:RENT:TYPES",
  DELETE_RENT_TYPES: "DELETE:RENT:TYPES",
  // Rent permissions
  READ_RENTS: "READ:RENTS",
  CREATE_RENTS: "CREATE:RENTS",
  EDIT_RENTS: "EDIT:RENTS",
  DELETE_RENTS: "DELETE:RENTS",
  // Asset permissions
  READ_ASSETS: "READ:ASSETS",
  CREATE_ASSETS: "CREATE:ASSETS",
  EDIT_ASSETS: "EDIT:ASSETS",
  DELETE_ASSETS: "DELETE:ASSETS",
  // Asset Transfer Permissions
  READ_ASSET_TRANSFERS: "READ:ASSET:TRANSFERS",
  CREATE_ASSET_TRANSFERS: "CREATE:ASSET:TRANSFERS",
  EDIT_ASSET_TRANSFERS: "EDIT:ASSET:TRANSFERS",
  DELETE_ASSET_TRANSFERS: "DELETE:ASSET:TRANSFERS",
  APPROVE_ASSET_TRANSFERS: "APPROVE:ASSET:TRANSFERS",

  // Attendance Report Permissions
  VIEW_ATTENDANCE_REPORTS: "VIEW:ATTENDANCE:REPORTS",

  // satrt
  PERMISSION_GROUPS: "PERMISSION_GROUPS",
  VIEW_ROLES: "VIEW:ROLES",
  EDIT_ROLES_PERMISSIONS: "EDIT:ROLES:PERMISSIONS",
  // end
} as const;

// Optional: manual grouping of permissions for UI sections. Some UI files import
// PERMISSION_GROUPS directly. Provide a minimal, safe default here so those
// imports work without changing existing call-sites. Consumers may override or
// extend this later if they need custom ordering/grouping.
export const PERMISSION_GROUPS: {
  key: string;
  label: string;
  permissions: string[];
}[] = [];

export const ROLES = {
  ADMIN: "Admin",
  SITE_ADMIN: "Site Admin",
  COMMERCIAL_HEAD: "Commercial Head",
  MANAGING_DIRECTOR: "Managing Director",
  SITE_INCHARGE: "Site Incharge",
  OFFICE_ASSISTANT: "Office Assistant",
  TECHNICAL_SUPPORT: "Technical Support",
  TRAINEE_ENGINEER: "Trainee Engineer",
  ACCOUNT_EXECUTIVE: "Account Executive",
  JUNIOR_ACCOUNTANT: "Junior Accountant",
  SENIOR_HR_EXECUTIVE: "Senior HR Executive",
  SITE_SUPERVISOR: "Site Supervisor",
  PROJECT_DIRECTOR: "Project Director",
  HR_ASSISTANT: "HR Assistant",

  ASSISTANT_ENGINEER: "Assistant Engineer",
  TENDER_EXECUTIVE: "Tender Executive",
  SENIOR_PROJECT_MANAGER: "Senior Project Manager",
  JUNIOR_ENGINEER: "Junior Engineer",
  WORK_ASSISTANT: "Work Assistant",
  SAFETY_SUPERVISOR: "Safety Supervisor",
  SENIOR_SITE_SUPERVISOR: "Senior Site Supervisor",
  PROJECT_ENGINEER: "Project Engineer",

  ASSISTANT_MANAGER_PROJECTS: "Assistant Manager - Projects",
  SENIOR_ACCOUNTANT: "Senior Accountant",
  ASSISTANT_MANAGER: "Assistant Manager",
  DIRECTOR: "Director",
  SENIOR_PROJECT_ENGINEER: "Senior Project Engineer",
  MECHANIC: "Mechanic",
  PROJECT_COORDINATOR: "Project Coordinator",
  PURCHASE_EXECUTIVE: "Purchase Executive",
  ELECTRICIAN: "Electrician",
  SCAFFOLDING_INSPECTOR: "Scaffolding Inspector",
  ESTIMATION_ENGINEER: "Estimation Engineer",
  ACCOUNT_ASSISTANT: "Account Assistant",
  PROJECT_MANAGER: "Project Manager",
  ASSISTANT_MANAGER_EHS: "Assistant Manager - EHS",
  GENERAL_MANAGER_FINANCE_ADMIN_COMM: "General Manager (Finance, Admin, Comm)",
  DIVING_SUPERVISOR: "Diving Supervisor",
  TECHNICAL_DIRECTOR: "Technical Director",
} as const;

export const ROLES_PERMISSIONS = {
  // Admin: everything
  [ROLES.ADMIN]: [...Object.values(PERMISSIONS)],
  [ROLES.SITE_INCHARGE]: [...Object.values(PERMISSIONS)],

  // Internal staff user: can view dashboard, read users & projects & project files (but no creation/upload/delete)

  [ROLES.TECHNICAL_SUPPORT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.MANAGING_DIRECTOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.COMMERCIAL_HEAD]: [
    PERMISSIONS.READ_STOCK_ADJUSTMENTS,
    PERMISSIONS.CREATE_STOCK_ADJUSTMENTS,
    PERMISSIONS.VIEW_STOCK_ADJUSTMENTS,
    PERMISSIONS.READ_STOCKS,
    PERMISSIONS.VIEW_STOCKS,

    PERMISSIONS.READ_ASSET_TRANSFERS,
    PERMISSIONS.CREATE_ASSET_TRANSFERS,
    PERMISSIONS.EDIT_ASSET_TRANSFERS,
    PERMISSIONS.APPROVE_ASSET_TRANSFERS,
    PERMISSIONS.DELETE_ASSET_TRANSFERS,

    PERMISSIONS.CREATE_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.DELETE_ASSETS,
    PERMISSIONS.READ_ASSET_GROUPS,
    PERMISSIONS.READ_ASSET_CATEGORIES,
    PERMISSIONS.READ_ASSETS,
    PERMISSIONS.READ_DAILY_PROGRESSES,
    PERMISSIONS.EDIT_DAILY_PROGRESSES,
    PERMISSIONS.DELETE_DAILY_PROGRESSES,

    PERMISSIONS.READ_DAILY_CONSUMPTIONS,
    PERMISSIONS.CREATE_DAILY_CONSUMPTIONS,
    PERMISSIONS.VIEW_DAILY_CONSUMPTIONS,

    PERMISSIONS.EDIT_BOQS,
    PERMISSIONS.DELETE_BOQS,
    PERMISSIONS.READ_INWARD_BILL,
    PERMISSIONS.EDIT_INWARD_BILL,

    PERMISSIONS.READ_SITE_BUDGETS,
    PERMISSIONS.CREATE_SITE_BUDGETS,
    PERMISSIONS.EDIT_SITE_BUDGETS,
    PERMISSIONS.DELETE_SITE_BUDGETS,

    PERMISSIONS.READ_OUTWARD_DELIVERY_CHALLAN,
    PERMISSIONS.CREATE_OUTWARD_DELIVERY_CHALLAN,
    PERMISSIONS.APPROVE_OUTWARD_DELIVERY_CHALLAN,
    PERMISSIONS.ACCEPT_OUTWARD_DELIVERY_CHALLAN,

    PERMISSIONS.READ_INWARD_DELIVERY_CHALLAN,
    PERMISSIONS.CREATE_INWARD_DELIVERY_CHALLAN,
    PERMISSIONS.EDIT_INWARD_DELIVERY_CHALLAN,

    PERMISSIONS.READ_VENDORS,
    PERMISSIONS.READ_PAYMENT_TERMS,
    PERMISSIONS.READ_BILLING_ADDRESSES,
    PERMISSIONS.SUSPEND_PURCHASE_ORDERS,
    PERMISSIONS.APPROVE_PURCHASE_ORDERS_L1,
    PERMISSIONS.APPROVE_PURCHASE_ORDERS_L2,
    PERMISSIONS.COMPLETE_PURCHASE_ORDERS,
    PERMISSIONS.SUSPEND_PURCHASE_ORDERS,

    PERMISSIONS.READ_PURCHASE_ORDERS,
    PERMISSIONS.CREATE_PURCHASE_ORDERS,
    PERMISSIONS.EDIT_PURCHASE_ORDERS,
    PERMISSIONS.DELETE_PURCHASE_ORDERS,

    PERMISSIONS.READ_UNITS,
    PERMISSIONS.READ_ITEM_CATEGORIES,

    PERMISSIONS.READ_ITEMS,

    PERMISSIONS.READ_INDENTS,
    PERMISSIONS.CREATE_INDENTS,
    PERMISSIONS.EDIT_INDENTS,
    PERMISSIONS.DELETE_INDENTS,

    PERMISSIONS.APPROVE_INDENTS_L1,
    PERMISSIONS.APPROVE_INDENTS_L2,
    PERMISSIONS.COMPLETE_INDENTS,
    PERMISSIONS.SUSPEND_INDENTS,
    PERMISSIONS.GENERATE_PO_FROM_INDENT,

    PERMISSIONS.READ_CASHBOOK_BUDGETS,
    PERMISSIONS.CREATE_CASHBOOK_BUDGETS,
    PERMISSIONS.EDIT_CASHBOOK_BUDGETS,
    PERMISSIONS.DELETE_CASHBOOK_BUDGETS,

    PERMISSIONS.READ_BOQS,

    PERMISSIONS.READ_CASHBOOK_HEADS,
    PERMISSIONS.READ_CASHBOOKS,
    PERMISSIONS.CREATE_CASHBOOKS,
    PERMISSIONS.EDIT_CASHBOOKS,
    PERMISSIONS.DELETE_CASHBOOKS,

    PERMISSIONS.READ_RENTAL_CATEGORIES,
    PERMISSIONS.READ_RENT_TYPES,

    PERMISSIONS.READ_RENTS,
    PERMISSIONS.CREATE_RENTS,
    PERMISSIONS.EDIT_RENTS,
    PERMISSIONS.DELETE_RENTS,

    PERMISSIONS.VIEW_MANPOWER_TRANSFERS,
    PERMISSIONS.READ_MANPOWER_TRANSFERS,
    PERMISSIONS.CREATE_MANPOWER_TRANSFERS,
    PERMISSIONS.EDIT_MANPOWER_TRANSFERS,
    PERMISSIONS.DELETE_MANPOWER_TRANSFERS,

    PERMISSIONS.READ_ATTENDANCES,
    PERMISSIONS.CREATE_ATTENDANCES,
    PERMISSIONS.EDIT_ATTENDANCES,
    PERMISSIONS.DELETE_ATTENDANCES,
    PERMISSIONS.VIEW_ATTENDANCES,

    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_SITES,
    PERMISSIONS.READ_SITES,
    PERMISSIONS.CREATE_SITES,
    PERMISSIONS.EDIT_SITES,
    PERMISSIONS.DELETE_SITES,
    PERMISSIONS.READ_EMPLOYEES,

    PERMISSIONS.EDIT_EMPLOYEES,
    PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.CREATE_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.EDIT_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.VIEW_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.DELETE_MANPOWER_ASSIGNMENTS,
    PERMISSIONS.READ_MANPOWER,

    PERMISSIONS.READ_SKILLSETS,

    PERMISSIONS.READ_MANPOWER_SUPPLIERS,
    PERMISSIONS.READ_CATEGORIES,

    PERMISSIONS.EDIT_MANPOWER,
    // PERMISSIONS.DELETE_MANPOWER,
    PERMISSIONS.VIEW_MANPOWER,
  ],
  [ROLES.SITE_ADMIN]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.TRAINEE_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ACCOUNT_EXECUTIVE]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.JUNIOR_ACCOUNTANT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],

  [ROLES.SENIOR_HR_EXECUTIVE]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SITE_SUPERVISOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.PROJECT_DIRECTOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.HR_ASSISTANT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ASSISTANT_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.TENDER_EXECUTIVE]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SENIOR_PROJECT_MANAGER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.JUNIOR_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.WORK_ASSISTANT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SAFETY_SUPERVISOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SENIOR_SITE_SUPERVISOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.PROJECT_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ASSISTANT_MANAGER_PROJECTS]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SENIOR_ACCOUNTANT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ASSISTANT_MANAGER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.DIRECTOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SENIOR_PROJECT_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.MECHANIC]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.PROJECT_COORDINATOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.PURCHASE_EXECUTIVE]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ELECTRICIAN]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.SCAFFOLDING_INSPECTOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ESTIMATION_ENGINEER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ACCOUNT_ASSISTANT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.PROJECT_MANAGER]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ASSISTANT_MANAGER_EHS]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.GENERAL_MANAGER_FINANCE_ADMIN_COMM]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.DIVING_SUPERVISOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.TECHNICAL_DIRECTOR]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.OFFICE_ASSISTANT]: [
    // DASHBOARD
    PERMISSIONS.VIEW_DASHBOARD,
  ],

  // Project (client) user: minimal permissions
  // [ROLES.TECHNICAL_SUPPORT]: [
  //   PERMISSIONS.VIEW_DASHBOARD,
  //   PERMISSIONS.READ_CITIES,
  //   PERMISSIONS.READ_STATES,
  //   PERMISSIONS.READ_COMPANIES,
  //   PERMISSIONS.READ_SITES,
  //   PERMISSIONS.READ_DEPARTMENTS,
  //   PERMISSIONS.READ_EMPLOYEES,
  //   PERMISSIONS.READ_MANPOWER_SUPPLIERS,
  //   PERMISSIONS.READ_MANPOWER,
  //   PERMISSIONS.READ_CATEGORIES,
  //   PERMISSIONS.READ_SKILLSETS,
  //   PERMISSIONS.READ_MIN_WAGES,
  //   PERMISSIONS.READ_UNITS,
  //   PERMISSIONS.READ_ASSET_GROUPS,
  //   PERMISSIONS.READ_ASSET_CATEGORIES,
  //   PERMISSIONS.READ_ITEM_CATEGORIES,
  //   PERMISSIONS.READ_ITEMS,
  //   PERMISSIONS.READ_BILLING_ADDRESSES,
  //   PERMISSIONS.READ_VENDORS,
  //   PERMISSIONS.READ_BOQS,
  //   PERMISSIONS.READ_PAYMENT_TERMS,
  //   PERMISSIONS.READ_CASHBOOK_HEADS,
  //   PERMISSIONS.READ_CASHBOOK_BUDGETS,
  //   PERMISSIONS.READ_CASHBOOKS,
  //   PERMISSIONS.READ_INDENTS,
  //   PERMISSIONS.READ_SITE_BUDGETS,
  //   PERMISSIONS.READ_RENTAL_CATEGORIES,
  //   PERMISSIONS.READ_RENT_TYPES,
  //   PERMISSIONS.READ_RENTS,
  //   PERMISSIONS.READ_ASSETS,
  //   PERMISSIONS.READ_ASSET_TRANSFERS,
  //   PERMISSIONS.READ_MANPOWER_ASSIGNMENTS,
  //   PERMISSIONS.READ_MANPOWER_TRANSFERS,
  //   PERMISSIONS.READ_NOTICES,
  //   PERMISSIONS.READ_ATTENDANCES,
  //   // keep create_attendances on project_user as in yash (remove if clients shouldn't create attendance)
  //   PERMISSIONS.CREATE_ATTENDANCES,

  //   // Payroll (view-only)
  //   PERMISSIONS.READ_PAYSLIPS,
  //   PERMISSIONS.VIEW_ATTENDANCE_REPORTS,
  // ],
} as const;
